### ISSUE TITLE
gccgo can be replaced to a bbappend for GCC

### ISSUE THREAD

**Issue by otavio** [digitallumens/meta-golang#3]
The GCC now offers support for Go so we ought to use the built-in one instead of the set of patches.

**Comment by celledge** [comment]
That was already true, I was originally experimenting to see how I could get cross compiling to work. I could probably redesign it as a bbappend when I have some time to test it out.

**Comment by celledge** [comment]
I've done some preliminary work on a BBAPPEND based recipe against gcc_4.9 in fido. It's in the bbappend branch of this project.

**Comment by celledge** [comment]
I'm abandoning the gccgo approach for now. It's been too much of a headache to support. I've got the gc compiler working nicely with statically compiled executables in the go-1.7 and current master branches.
